module.exports = {
    projects: [
        ,
        '<rootDir>/apps/store',
        '<rootDir>/libs/ui',
        '<rootDir>/libs/nest/admin/products',
        '<rootDir>/libs/nest/common/prisma',
        '<rootDir>/libs/nest/admin/users',
        '<rootDir>/libs/nest/server/auth',
        '<rootDir>/libs/nest/common/password',
        '<rootDir>/libs/nest/common/configs',
        '<rootDir>/libs/ui/src/libs',
        '<rootDir>/libs/ui/src/libs/icons',
        '<rootDir>/libs/ui/src/theme',
        '<rootDir>/libs/ui/src/icons',
        '<rootDir>/libs/ui/src/components',
        '<rootDir>/libs/=ui/src/animations',
        '<rootDir>/libs/ui/src/animations',
        '<rootDir>/libs/nest/graphql',
        '<rootDir>/libs/shared',
        '<rootDir>/libs/nest/admin/roles',
        '<rootDir>/libs/nest/admin/permissions',
        '<rootDir>/libs/nest/common/i18n',
        '<rootDir>/apps/api/server',
        '<rootDir>/apps/api/admin',
        '<rootDir>/libs/nest/server/users',
    ],
}
