module.exports = {
    projects: [
        ,
        '<rootDir>/apps/store',
        '<rootDir>/apps/api',
        '<rootDir>/libs/ui',
        '<rootDir>/libs/products',
        '<rootDir>/libs/prisma',
        '<rootDir>/libs/users',
        '<rootDir>/libs/auth',
        '<rootDir>/libs/password',
        '<rootDir>/libs/configs',
        '<rootDir>/libs/ui/src/libs',
        '<rootDir>/libs/ui/src/libs/icons',
        '<rootDir>/libs/ui/src/theme',
        '<rootDir>/libs/ui/src/icons',
        '<rootDir>/libs/ui/src/components',
        '<rootDir>/libs/chat',
        '<rootDir>/libs/=ui/src/animations',
        '<rootDir>/libs/ui/src/animations',
    ],
}
