module.exports = {
    projects: [
        ,
        '<rootDir>/apps/store',
        '<rootDir>/apps/api',
        '<rootDir>/libs/ui',
        '<rootDir>/libs/nest/products',
        '<rootDir>/libs/nest/prisma',
        '<rootDir>/libs/nest/users',
        '<rootDir>/libs/nest/auth',
        '<rootDir>/libs/nest/password',
        '<rootDir>/libs/nest/configs',
        '<rootDir>/libs/ui/src/libs',
        '<rootDir>/libs/ui/src/libs/icons',
        '<rootDir>/libs/ui/src/theme',
        '<rootDir>/libs/ui/src/icons',
        '<rootDir>/libs/ui/src/components',
        '<rootDir>/libs/=ui/src/animations',
        '<rootDir>/libs/ui/src/animations',
        '<rootDir>/libs/nest/graphql',
        '<rootDir>/libs/shared',
        '<rootDir>/libs/nest/role',
        '<rootDir>/libs/nest/permission',
    ],
}
